apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: game-server
spec:
  selector:
    matchLabels:
      app: game-server
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: game-server
        tier: frontend
    spec:
      containers:
      - name: game-server
        image: registry-vpc.cn-beijing.aliyuncs.com/shoutan/game-server:0.2
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: service-config
      imagePullSecrets:
      - name: aliyun-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: game-server
  labels:
    app: game-server
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: game-server
    tier: frontend
